# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '7e9ae4d017187fe2dc3963762914390e'
  config.secret_key = 'b8ee98ac1db6949200e20236afb46a2d'
  config.default_from = 'remilp@hotmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
